# 🚀 NETLIFY DEPLOY CONFIG - Alternativa ao netlify.toml
build:
  publish: dist
  command: npm run build
  environment:
    NODE_VERSION: "18"
    NODE_ENV: "production"
    NPM_FLAGS: "--include=dev"

# Headers para otimização
headers:
  - for: "/*"
    values:
      X-Frame-Options: "DENY"
      X-Content-Type-Options: "nosniff"
      Referrer-Policy: "strict-origin-when-cross-origin"
      
  - for: "/assets/*"
    values:
      Cache-Control: "public, max-age=31536000, immutable"
      
  - for: "/*.js"
    values:
      Cache-Control: "public, max-age=31536000, immutable"
      
  - for: "/*.css"
    values:
      Cache-Control: "public, max-age=31536000, immutable"

# Redirects
redirects:
  - from: "/*"
    to: "/index.html"
    status: 200
